# Generated by Django 2.0.2 on 2019-05-08 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likecount',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='likerecord',
            name='comment',
        ),
    ]
