# Generated by Django 2.2 on 2019-05-09 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_auto_20190508_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likecount',
            name='blog',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog'),
        ),
    ]
