# Generated by Django 2.0.2 on 2019-04-24 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190424_2135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReadNum',
            new_name='ViewedNum',
        ),
    ]
