# Generated by Django 2.0.2 on 2019-04-24 15:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190424_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewedDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('viewed_num', models.IntegerField(default=0)),
            ],
        ),
    ]
