# Generated by Django 2.0.2 on 2019-04-30 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_vieweddetail_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vieweddetail',
            name='blog',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Blog'),
        ),
    ]
